.TH CREDIT-CLI "1" "November 2016" "credit-cli 1.0"
.SH NAME
credit-cli \- a remote procedure call client for Credit. 
.SH SYNOPSIS
credit-cli [options] <command> [params] \- Send command to Credit. 
.TP
credit-cli [options] help \- Asks Credit for a list of supported commands.
.SH DESCRIPTION
This manual page documents the credit-cli program. credit-cli is an RPC client used to send commands to Credit.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
